Repository McNamara84/elmo, pull requests merged in 2024-12, with the labels that each got.

#242 Feature: About and Changelog
  doc/changelog.html
  footer.html
  header.html
  js/buttons.js
  js/validation.js
  tests/SeleniumTests/Tests_MDE.side
Labels: Dokumentation, Feature Request

#244 Feature: Hide lab affiliation from user
  README.md
  formgroups/originatingLaboratory.html
Labels: Dokumentation, Feature Request

#240 Bugfix: Speicherung der Rollen von Contributors
  save/formgroups/save_contributors.php
Labels: bug

#247 Bugfix: Autocomplete für geklonte Zeilen in Funders Reference
  js/buttons.js
  js/select.js
Labels: bug

#249 Dokumentation: Lizenzwechsel zu GPLv2
  CITATION.cff
  CONTRIBUTORS.md
  LICENSE.md
  api/v2/docs/swagger.yaml
  composer.json
  vendor/composer/installed.php
Labels: Dokumentation

#250 Feature: Custom filename for XML download
  doc/changelog.html
  footer.html
  index.php
  js/validation.js
  lang/de.php
  lang/en.php
  lang/fr.php
  modals.html
  save/save_data.php
Labels: Feature Request

#260 Fix/map2datacite
  doc/changelog.html
  doc/help.html
  formgroups/resourceInformation.html
  formgroups/rights.html
  formgroups/spatialtemporalcoverage.html
  install.php
  save/formgroups/save_affiliations.php
  schemas/Freestyle/FreestyleSchemaDB.xsd
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
  tests/SeleniumTests/Tests_MDE.side
  vendor/composer/installed.php
  xml/dataset2.xml
  xml/dataset3.xml
  xml/dataset4.xml
Labels: bug

#256 Feature: Load XML
  .github/workflows/php82.yml
  .github/workflows/php83.yml
  .github/workflows/php84.yml
  composer.lock
  css/gfz-cd.css
  doc/changelog.html
  footer.html
  js/buttons.js
  js/mappingXmlToInputFields.js
  js/upload.js
  modals.html
  tests/datasets/dataset1.xml
  tests/datasets/dataset2.xml
  tests/datasets/dataset3.xml
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
Labels: Dokumentation, Feature Request

#287 Feature: Mandatory fields
  README.md
  doc/changelog.html
  formgroups/authors.html
  formgroups/contactpersons.html
  formgroups/contributors.html
  formgroups/fundingreference.html
  js/buttons.js
  js/checkMandatoryFields.js
Labels: bug, Feature Request

#365 Feature: Templates für Pull Requests
  .github/PULL_REQUEST_REVIEW_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  vendor/composer/installed.php
Labels: Dokumentation

#369 Feature: Link to imprint
  api/v2/docs/swagger.yaml
  css/help.css
  doc/changelog.html
  doc/help.html
  header.html
  lang/de.php
  lang/en.php
  lang/fr.php
Labels: Feature Request
