Repository McNamara84/elmo, pull requests merged in 2024-11, with the labels that each got.

#137 Fehlermeldung bei deaktiviertem JavaScript
  formgroups/resourceInformation.html
  lang/de.php
  lang/en.php
  lang/fr.php
Labels: Feature Request

#120 Automatisierte Tests
  .github/workflows/php.yml
  install.php
  save/formgroups/save_authors.php
  save/formgroups/save_fundingreferences.php
  save/formgroups/save_relatedwork.php
  tests/SaveAuthorsTest.php
  tests/SaveContactpersonsTest.php
  tests/SaveContributorsTest.php
  tests/SaveDescriptionsTest.php
  tests/SaveFreekeywordsTest.php
  tests/SaveFundingreferencesTest.php
  tests/SaveOriginatingLaboratoryTest.php
  tests/SaveRelatedworkTest.php
  tests/SaveResourceInformationAndRightsTest.php
  tests/SaveSpatialTemporalCoverageTest.php
  tests/SaveThesauruskeywordsTest.php
Labels: Feature Request

#139 Bugfixes Sprint 3
  .htaccess
  README.md
  api/v2/docs/swagger.yaml
  api/v2/index.php
  doc/help.html
  formgroups/authors.html
  formgroups/contributors.html
  formgroups/resourceInformation.html
  formgroups/spatialtemporalcoverage.html
  js/buttons.js
  lang/de.php
  lang/en.php
  lang/fr.php
Labels: Dokumentation, Feature Request

#155 Fix/fg originating laboratory
  formgroups/originatingLaboratory.html
  js/autocomplete.js
  js/buttons.js
Labels: bug, Feature Request

#153 Pull Request zum Brunch "Future/tagify roles felder"
  footer.html
  formgroups/contributors.html
  js/buttons.js
  js/roles.js
  js/select.js
Labels: bug, Feature Request

#169 Selenium tests
  tests/SeleniumTests/Tests_MDE.side
Labels: Feature Request

#177 Fix/thesauri
  doc/help.html
  formgroups/mslKeywords.html
  js/thesauri.js
  lang/de.php
  lang/en.php
  lang/fr.php
Labels: bug

#176 ORCID Preload for Authors and Contributors
  README.md
  composer.lock
  doc/help.html
  formgroups/authors.html
  formgroups/contributors.html
  js/affiliations.js
  js/autocomplete.js
  js/buttons.js
  lang/de.php
  lang/en.php
  lang/fr.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php
  vendor/myclabs/deep-copy/src/DeepCopy/TypeFilter/Date/DatePeriodFilter.php
Labels: Dokumentation, Feature Request

#179 API Anpassungen
  README.md
  api/v2/controllers/VocabController.php
  api/v2/docs/swagger.yaml
  api/v2/routes/api.php
  js/thesauri.js
  json/gcmdInstrumentsKeywords.json
  json/gcmdPlatformsKeywords.json
  json/gcmdScienceKeywords.json
  json/msl-vocabularies.json
  tests/ApiTest.php
Labels: bug, Dokumentation, Feature Request

#188 Fix/doi hinweis+pflichtfeldmarkierungen
  doc/help.html
  formgroups/authors.html
  formgroups/dates.html
  formgroups/descriptions.html
  formgroups/fundingreference.html
  formgroups/mslKeywords.html
  formgroups/resourceInformation.html
  formgroups/spatialtemporalcoverage.html
  formgroups/thesaurusKeywords.html
  lang/de.php
  lang/en.php
  lang/fr.php
Labels: bug, Feature Request

#181 Mapping-Anpassungen
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
Labels: bug, Feature Request

#189 Thesaurus GUI Fix
  css/bs5-chosen.css
  css/tagify-adj.css
  formgroups/freeKeywords.html
  formgroups/mslKeywords.html
  formgroups/thesaurusKeywords.html
  header.html
  js/thesauri.js
Labels: bug

#175 Main Title & Feedback Formular
  doc/help.html
  formgroups/resourceInformation.html
  js/buttons.js
  lang/de.php
  lang/en.php
  lang/fr.php
  send_feedback_mail.php
Labels: Feature Request, Feedback Tool

#191 Diverse Bugfixes
  doc/help.html
  formgroups/contributors.html
  formgroups/freeKeywords.html
  formgroups/mslKeywords.html
  formgroups/thesaurusKeywords.html
  js/affiliations.js
  tests/SeleniumTests/Tests_MDE.side
Labels: bug, Dokumentation

#195 Testautomatisierung von Selenium-Tests und Unterstützung für neue PHP-Versionen
  .github/workflows/php82.yml
  .github/workflows/php83.yml
  .github/workflows/php84.yml
  .github/workflows/selenium.yml
  README.md
  api/v2/controllers/VocabController.php
  composer.json
  composer.lock
  tests/SeleniumTests/Tests_MDE.side
  vendor/composer/installed.php
Labels: Feature Request

#212 Fix für HTML-Attribute
  README.md
  footer.html
  formgroups/contributors.html
  formgroups/fundingreference.html
  formgroups/relatedwork.html
  header.html
  js/buttons.js
Labels: bug, Dokumentation

#236 Bugfix: Geklonte Zeilen für Contact Persons haben kein funktionierendes Affiliations-Feld
  formgroups/contactpersons.html
  js/buttons.js
Labels: bug, Dokumentation
