Repository McNamara84/elmo, pull requests merged in 2025-03, with the labels that each got.

#564 Versionsnummer auf v2.0.0 erhöht
  doc/changelog.html
  lang/de.json
  lang/en.json
  lang/fr.json
  vendor/composer/InstalledVersions.php
  vendor/composer/installed.php
Labels: Dokumentation

#567 Fix: Early loading of Tagify for affiliations
  doc/changelog.html
  js/buttons.js
  js/mappingXmlToInputFields.js
  js/roles.js
Labels: bug

#576 Better XML + Saving Contributors
  doc/changelog.html
  doc/help.html
  save/formgroups/save_contributorpersons.php
  save/validation.php
  schemas/Mappings/FreestyleToISO.mfd
  schemas/XSLT/MappingMapToIso.xslt
  send_xml_file.php
Labels: bug

#581 Fix: Language marker in language settings
  doc/changelog.html
  js/buttons.js
  js/language.js
Labels: bug

#580 Fix: New main menu for ELMO User Guide
  doc/changelog.html
  doc/help.html
  doc/helpMenu.js
  formgroups/contributorInstitutions.html
  formgroups/contributorPersons.html
  js/affiliations.js
  js/autocomplete.js
  js/buttons.js
  js/checkMandatoryFields.js
  js/help.js
  tests/SeleniumTests/Tests_MDE.side
Labels: bug, Dokumentation
