Repository McNamara84/elmo, pull requests merged in 2025-02, with the labels that each got.

#470 Fix formgroup stc
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/coverage.html
  install.php
  js/buttons.js
  js/checkMandatoryFields.js
  js/language.js
  js/mappingXmlToInputFields.js
  lang/de.json
  lang/en.json
  lang/fr.json
  save/formgroups/save_spatialtemporalcoverage.php
  schemas/Freestyle/FreestyleSchemaDB.xsd
Labels: Feature Request

#464 Feature: Option to install database without test datasets
  .github/workflows/php82.yml
  .github/workflows/php83.yml
  .github/workflows/php84.yml
  README.md
  composer.lock
  css/gfz-cd.css
  doc/changelog.html
  install.html
  install.php
  js/install.js
  tests/ApiTest.php
  tests/SaveAuthorsTest.php
  tests/SaveContactpersonsTest.php
  tests/SaveContributorsTest.php
  tests/SaveDescriptionsTest.php
  tests/SaveFreekeywordsTest.php
  tests/SaveFundingreferencesTest.php
  tests/SaveOriginatingLaboratoryTest.php
  tests/SaveRelatedworkTest.php
  tests/SaveResourceInformationAndRightsTest.php
  tests/SaveSpatialTemporalCoverageTest.php
  tests/SaveThesauruskeywordsTest.php
  tests/TestDatabaseSetup.php
  vendor/composer/installed.php
Labels: Dokumentation, Feature Request

#510 Fix: Anpassungen an neue Corporate Identity des GFZ
  README.md
  api/v2/controllers/VocabController.php
  api/v2/docs/swagger.yaml
  composer.json
  doc/help.html
  favicon.ico
  header.html
  install.php
  lang/de.json
  lang/en.json
  lang/fr.json
  metadata_template.xml
  schemas/Mappings/FreestyleToISO.mfd
  schemas/XSLT/MappingMapToIso.xslt
  tests/datasets/dataset1.xml
  tests/datasets/dataset2.xml
  tests/datasets/dataset3.xml
Labels: bug, Dokumentation

#463 Feature: privacy policy
  composer.lock
  css/gfz-cd.css
  doc/changelog.html
  doc/help.html
  doc/privacyPolicy.html
  header.html
Labels: Dokumentation, Feature Request

#513 Feature: Optional form groups
  README.md
  composer.lock
  doc/changelog.html
  doc/help.html
  index.php
  js/buttons.js
  js/map.js
  js/thesauri.js
  sample_settings.php
  vendor/composer/installed.php
Labels: Dokumentation, Feature Request

#521 Anreicherung help guide
  README.md
  doc/help.html
Labels: Dokumentation

#519 Fix: DataCite Mapping
  README.md
  doc/changelog.html
  js/checkMandatoryFields.js
  save/formgroups/save_fundingreferences.php
  save/formgroups/save_spatialtemporalcoverage.php
  schemas/Freestyle/FreestyleSchemaDB.xsd
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
Labels: bug

#527 Fix/helpbuttons title
  doc/changelog.html
  js/buttons.js
  js/help.js
Labels: bug

#517 Lizenzen&tooltips
  doc/changelog.html
  doc/help.html
  footer.html
  install.php
  js/language.js
Labels: bug, Feature Request

#544 Fix: Charset encoding for MSL labs
  api/v2/controllers/VocabController.php
  doc/changelog.html
  json/msl-labs.json
  vendor/composer/installed.php
Labels: bug

#547 enable clear button
  footer.html
Labels: bug

#548 Fix: Trigger submitting with enter command in submit modal
  doc/changelog.html
  js/submitHandler.js
Labels: bug

#537 Fix: Better MappingToISO
  .github/workflows/php82.yml
  .github/workflows/php83.yml
  .github/workflows/php84.yml
  api.php
  api/v2/controllers/DatasetController.php
  api/v2/controllers/VocabController.php
  composer.lock
  doc/changelog.html
  js/thesauri.js
  json/gcmdInstrumentsKeywords.json
  json/gcmdPlatformsKeywords.json
  json/gcmdScienceKeywords.json
  json/msl-vocabularies.json
  json/thesauri/ChronostratKeywords.json
  json/thesauri/cgi.json
  json/thesauri/gcmdInstrumentsKeywords.json
  json/thesauri/gcmdPlatformsKeywords.json
  json/thesauri/gcmdScienceKeywords.json
  json/thesauri/gemet.json
  json/thesauri/msl-vocabularies.json
  schemas/Freestyle/FreestyleSchemaDB.xsd
  schemas/Mappings/FreestyleToISO.mfd
  schemas/XSLT/MappingMapToIso.xslt
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/phpunit/phpunit/.phive/phars.xml
  vendor/phpunit/phpunit/ChangeLog-11.5.md
  vendor/phpunit/phpunit/composer.json
  vendor/phpunit/phpunit/composer.lock
  vendor/phpunit/phpunit/src/Framework/Constraint/String/StringContains.php
  vendor/phpunit/phpunit/src/Framework/MockObject/Generator/Generator.php
  vendor/phpunit/phpunit/src/Framework/TestCase.php
  vendor/phpunit/phpunit/src/Framework/TestRunner/ChildProcessResultProcessor.php
  vendor/phpunit/phpunit/src/Framework/TestRunner/SeparateProcessTestRunner.php
  vendor/phpunit/phpunit/src/Framework/TestRunner/templates/class.tpl
  vendor/phpunit/phpunit/src/Framework/TestRunner/templates/method.tpl
  vendor/phpunit/phpunit/src/Runner/PHPT/PhptTestCase.php
  vendor/phpunit/phpunit/src/Runner/Version.php
  vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/Loader.php
  vendor/phpunit/phpunit/src/Util/PHP/DefaultJobRunner.php
  vendor/phpunit/phpunit/src/Util/PHP/JobRunner.php
  vendor/phpunit/phpunit/src/Util/PHP/JobRunnerRegistry.php
  vendor/phpunit/phpunit/tests/end-to-end/event/unexpected-end-of-test-in-separate-process.phpt
  vendor/phpunit/phpunit/tests/unit/Framework/TestRunner/ChildProcessResultProcessorTest.php
  vendor/phpunit/phpunit/tests/unit/Util/PHP/DefaultJobRunnerTest.php
  vendor/phpunit/phpunit/tools/php-cs-fixer
Labels: bug

#540 Keywords modal
  README.md
  css/gfz-cd.css
  doc/changelog.html
  doc/help.html
  formgroups/mslKeywords.html
  formgroups/thesaurusKeywords.html
  js/clear.js
  js/mappingXmlToInputFields.js
  js/thesauri.js
  lang/de.json
  lang/en.json
  lang/fr.json
  save/formgroups/save_thesauruskeywords.php
  save/save_data.php
  send_xml_file.php
  tests/SaveKeywordsTest.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: Feature Request

#555 Feature: Info for input filed Embargo until
  doc/changelog.html
  doc/egg.html
  doc/help.html
  lang/de.json
  lang/en.json
  lang/fr.json
Labels: Dokumentation, Feature Request

#550 Feature: Separate form groups for Contributor persons und Contributor Institutions
  doc/changelog.html
  formgroups/contributorInstitutions.html
  formgroups/contributorPersons.html
  index.php
  lang/de.json
  lang/en.json
  lang/fr.json
  vendor/composer/installed.php
Labels: Feature Request

#549 Feature: Better information in form group Descriptions
  doc/changelog.html
  formgroups/descriptions.html
  js/language.js
  lang/de.json
  lang/en.json
  lang/fr.json
  vendor/composer/installed.php
Labels: Dokumentation, Feature Request

#553 Doi feld anpassen
  css/gfz-cd.css
  doc/help.html
  formgroups/resourceInformation.html
  lang/de.json
  lang/en.json
  lang/fr.json
  vendor/composer/installed.php
Labels: Feature Request, Feedback

#563 Feature: Saving Originating Labs affiliations with ROR-ID
  README.md
  api/v2/controllers/VocabController.php
  doc/changelog.html
  formgroups/originatingLaboratory.html
  js/buttons.js
  js/mappingXmlToInputFields.js
  json/msl-labs.json
  sample_settings.php
  save/formgroups/save_originatinglaboratory.php
  tests/SaveOriginatingLaboratoryTest.php
Labels: Dokumentation, Feature Request

#559 Fix: Backend validation to prevent bad database entries
  doc/changelog.html
  save/formgroups/save_authors.php
  save/formgroups/save_contributorinstitutions.php
  save/formgroups/save_contributorpersons.php
  save/formgroups/save_contributors.php
  save/formgroups/save_descriptions.php
  save/formgroups/save_fundingreferences.php
  save/formgroups/save_originatinglaboratory.php
  save/formgroups/save_relatedwork.php
  save/formgroups/save_resourceinformation_and_rights.php
  save/formgroups/save_spatialtemporalcoverage.php
  save/formgroups/save_thesauruskeywords.php
  save/save_data.php
  save/validation.php
  tests/SaveContributorsTest.php
  tests/SaveKeywordsTest.php
  vendor/composer/installed.php
Labels: bug

#538 Feature: New workflow for contact person input
  README.md
  api/v2/controllers/DatasetController.php
  css/tagify-adj.css
  doc/ER-Diagram.jpg
  doc/help.html
  formgroups/authors.html
  formgroups/contactpersons.html
  index.php
  install.php
  js/affiliations.js
  js/buttons.js
  js/checkMandatoryFields.js
  js/clear.js
  js/mappingXmlToInputFields.js
  js/roles.js
  js/saveHandler.js
  js/submitHandler.js
  js/thesauri.js
  lang/de.json
  lang/en.json
  lang/fr.json
  save/formgroups/save_contactperson.php
  schemas/Freestyle/FreestyleSchemaDB.xsd
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
  tests/SaveContactpersonsTest.php
  vendor/composer/InstalledVersions.php
  vendor/composer/installed.php
  xml/resource_5.xml
Labels: Dokumentation, Feature Request

#560 Feature: Better validation for Dates
  api/v2/controllers/VocabController.php
  doc/help.html
  formgroups/coverage.html
  formgroups/dates.html
  js/freekeywordTags.js
  js/saveHandler.js
  js/submitHandler.js
  js/validation.js
  lang/de.json
  lang/en.json
  lang/fr.json
Labels: Dokumentation, Feature Request
