Repository McNamara84/elmo, pull requests merged in 2025-09, with the labels that each got.

#663 Feature: Frontend for new ICGEM form group Technical
  doc/changelog.html
  doc/help.html
  formgroups/GGMsProperties.html
  formgroups/GGMsTechnical.html
  index.php
  js/eventhandlers/buttons.js
  js/eventhandlers/formgroups/ggmproperties-technical.js
  lang/de.json
  lang/en.json
  lang/fr.json
Labels: Dokumentation, Feature Request

#693 Fix: corrected the required input fields ELMOGEM can save and submit data
  formgroups/GGMsTechnical.html
  formgroups/dataSources.html
  js/eventhandlers/formgroups/ggmproperties-technical.js
Labels: bug

#688 Fix: related work id patterns
  .gitignore
  js/affiliations.js
  js/select.js
  js/thesauri.js
Labels: bug

#709 Hotfix: reset the .dockerignore
  .dockerignore
Labels: bug

#716 Chore: Update dev templates
  .github/PULL_REQUEST_REVIEW_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Dokumentation, Abstimmung ausstehend

#717 Chore: Dependencies update for September
  composer.lock
  package-lock.json
Labels: Dokumentation

#718 Feature: Autosave drafts
  .gitignore
  README.md
  api/v2/controllers/DraftController.php
  api/v2/docs/swagger.yaml
  api/v2/index.php
  api/v2/routes/api.php
  css/gfz-cd.css
  doc/changelog.html
  footer.html
  js/eventhandlers/formgroups/author.js
  js/eventhandlers/formgroups/fundingreference.js
  js/eventhandlers/formgroups/relatedwork.js
  js/eventhandlers/formgroups/stc.js
  js/eventhandlers/functions.js
  js/language.js
  js/saveHandler.js
  js/services/autosaveService.js
  js/submitHandler.js
  js/validation.js
  lang/de.json
  lang/en.json
  lang/fr.json
  modals.html
  tests/DraftControllerTest.php
  tests/js/autosaveRepeaters.test.js
  tests/js/autosaveService.test.js
  tests/js/saveHandler.test.js
  tests/playwright/features/autosave.spec.ts
Labels: Feature Request

#734 Fix: Duplicate classes and IDs
  doc/changelog.html
  formgroups/authors.html
  js/eventhandlers/formgroups/author.js
  tests/js/authors.test.js
Labels: bug
