Repository McNamara84/elmo, pull requests merged in 2025-07, with the labels that each got.

#602 Feature: New formgroup for ICGEM essential data
  .DS_Store
  .dockerignore
  .env
  .gitignore
  .installed
  Dockerfile
  README.md
  api/.DS_Store
  api/v2/.DS_Store
  api/v2/controllers/DatasetController.php
  api/v2/controllers/VocabController.php
  api/v2/routes/api.php
  composer.lock
  doc/help.html
  docker-compose.yml
  docker-entrypoint.sh
  formgroups/GGMsProperties.html
  generate_xml_files.php
  index.php
  install.html
  install.php
  js/clear.js
  js/eventhandlers/buttons.js
  js/eventhandlers/formgroups/ggmproperties-essential.js
  js/install.js
  sample_settings.php
  save/formgroups/save_ggmsproperties.php
  save/formgroups/save_resourceinformation_and_rights.php
  save/save_data.php
  send_xml_file.php
  tests/ApiTest.php
  tests/DatabaseTestCase.php
  tests/SaveAuthorsTest.php
  tests/SaveContactpersonsTest.php
  tests/SaveContributorsTest.php
  tests/SaveDescriptionsTest.php
  tests/SaveFreekeywordsTest.php
  tests/SaveFundingreferencesTest.php
  tests/SaveGGMsProperties.php
  tests/SaveKeywordsTest.php
  tests/SaveOriginatingLaboratoryTest.php
  tests/SaveRelatedworkTest.php
  tests/SaveResourceInformationAndRightsTest.php
  tests/SaveSpatialTemporalCoverageTest.php
  xml/resource_3.xml
Labels: Dokumentation, Feature Request

#623 Hotfix: Install script is not working
  docker-compose.yml
  install.php
  js/install.js
  sample_settings.php
  save/save_data.php
  send_xml_file.php
Labels: bug

#624 Documentation: Badges in ReadMe
  .github/workflows/php84.yml
  README.md
  phpunit.xml
Labels: Dokumentation

#629 Testing: Unit testing for JavaScript functions
  .github/workflows/jest.yml
  README.md
  jest.config.js
  package-lock.json
  package.json
  tests/js/affiliations.test.js
Labels: Dokumentation, Feature Request

#630 API: Moved API endpoint for CGI Simple Lithology vocabulary to new APIv2
  api/v2/controllers/VocabController.php
  api/v2/docs/swagger.yaml
  api/v2/routes/api.php
  tests/ApiTest.php
Labels: Dokumentation, Feature Request

#631 Feature: Dynamically generate language dropdown
  README.md
  doc/changelog.html
  header.php
  index.php
Labels: Dokumentation, Feature Request

#618 Testing: More unit tests to increase code coverage
  composer.json
  composer.lock
  doc/changelog.html
  tests/FetchAndProcessCGIKeywordsTest.php
  tests/ParseAffiliationAndRorIdsTest.php
  tests/ValidationFunctionsTest.php
  tests/datasets/simplelithology.rdf
Labels: Dokumentation

#633 Fix: Coordinates from XML uploads will show up in map modal
  api/v2/controllers/DatasetController.php
  doc/changelog.html
  js/map.js
  js/mappingXmlToInputFields.js
  save/save_data.php
  send_xml_file.php
  tests/js/map.test.js
  tests/js/mappingXmlToInputFields.test.js
Labels: bug, Dokumentation

#632 Fix: save and submit buttons working propperly
  api/v2/controllers/DatasetController.php
  save/save_data.php
  send_xml_file.php
Labels: bug

#637 Chore: Moved jQuery from CDN to npm installation and unit tests for automcomplete.js
  README.md
  doc/help.html
  footer.html
  header.php
  package-lock.json
  package.json
  tests/js/affiliations.test.js
  tests/js/autocomplete.test.js
Labels: Dokumentation

#640 Feature: Add search to ELMO guide
  css/help.css
  doc/changelog.html
  doc/help.html
  doc/search.js
  package-lock.json
  package.json
  tests/js/helpMenu.test.js
  tests/js/search.test.js
Labels: Dokumentation, Feature Request

#641 Feature: New API endpoint /vocabs/resourcetypes
  api/v2/controllers/VocabController.php
  api/v2/docs/swagger.yaml
  api/v2/routes/api.php
  doc/changelog.html
  formgroups/resourceInformation.html
  index.php
  js/select.js
  tests/VocabControllerTest.php
  tests/js/select.test.js
Labels: Dokumentation, Feature Request

#649 Feature: New API endpoint for language of dataset options
  api/v2/controllers/VocabController.php
  api/v2/docs/swagger.yaml
  api/v2/routes/api.php
  formgroups/resourceInformation.html
  index.php
  js/mappingXmlToInputFields.js
  js/select.js
  tests/js/mappingXmlToInputFields.test.js
  tests/js/select.test.js
Labels: Dokumentation, Feature Request

#654 Fix: Translation of messages in save and submit workflow
  doc/changelog.html
  formgroups/authors.html
  formgroups/contributorPersons.html
  js/eventhandlers/formgroups/contributor-organisation.js
  js/eventhandlers/formgroups/contributor-person.js
  js/saveHandler.js
  js/submitHandler.js
  lang/de.json
  lang/en.json
  lang/fr.json
  tests/js/saveHandler.test.js
  tests/js/submitHandler.test.js
Labels: bug

#655 Fix: Initialization and translation of Tagify input fields optimized
  doc/changelog.html
  formgroups/contributorInstitutions.html
  formgroups/contributorPersons.html
  js/affiliations.js
  js/eventhandlers/formgroups/contributor-organisation.js
  js/eventhandlers/formgroups/contributor-person.js
  js/freekeywordTags.js
  js/roles.js
  tests/js/contributorOrganisation.test.js
  tests/js/contributorPerson.test.js
  tests/js/freekeywordTags.test.js
  tests/js/roles.test.js
Labels: bug
