Repository McNamara84/elmo, pull requests merged in 2025-01, with the labels that each got.

#374 Contact person
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/contactpersons.html
  formgroups/descriptions.html
  install.php
  js/checkMandatoryFields.js
  tests/SeleniumTests/Tests_MDE.side
Labels: Dokumentation, Feature Request

#366 Feature: Sortierbare Autoren
  README.md
  css/gfz-cd.css
  doc/help.html
  formgroups/authors.html
  js/buttons.js
  vendor/composer/installed.php
Labels: Feature Request

#377 Feature: Load to XML for Descriptions
  doc/changelog.html
  js/mappingXmlToInputFields.js
Labels: Feature Request

#376 Fix: Tagify Update auf Version 4.33.0
  README.md
  footer.html
  header.html
Labels: bug, Dokumentation

#383 Related work
  README.md
  doc/help.html
  formgroups/relatedwork.html
  js/buttons.js
  js/checkMandatoryFields.js
  js/mappingXmlToInputFields.js
  js/select.js
Labels: bug, Dokumentation, Feature Request

#389 Load Keywords
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/mslKeywords.html
  formgroups/thesaurusKeywords.html
  js/freekeywordTags.js
  js/mappingXmlToInputFields.js
  js/thesauri.js
Labels: Feature Request

#390 Fg stc
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/spatialtemporalcoverage.html
  js/mappingXmlToInputFields.js
Labels: Feature Request

#398 Fix: Saving created two data records in database
  js/validation.js
  save/save_data.php
Labels: bug

#382 Feature: New language management system
  composer.lock
  css/gfz-cd.css
  footer.html
  formgroups/authors.html
  formgroups/contactpersons.html
  formgroups/contributors.html
  formgroups/coverage.html
  formgroups/dates.html
  formgroups/descriptions.html
  formgroups/freeKeywords.html
  formgroups/fundingreference.html
  formgroups/mslKeywords.html
  formgroups/originatingLaboratory.html
  formgroups/relatedwork.html
  formgroups/resourceInformation.html
  formgroups/rights.html
  formgroups/thesaurusKeywords.html
  header.html
  index.php
  js/affiliations.js
  js/buttons.js
  js/freekeywordTags.js
  js/headerResponsiveDesign.js
  js/language.js
  js/roles.js
  js/select.js
  js/thesauri.js
  js/validation.js
  lang/de.json
  lang/de.php
  lang/en.json
  lang/en.php
  lang/fr.json
  lang/fr.php
  modals.html
  vendor/composer/installed.php
Labels: bug, Dokumentation, Feature Request

#407 update Mapping 2 DataCite
  api/v2/controllers/DatasetController.php
  schemas/Freestyle/FreestyleSchemaDB.xsd
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
  tests/SeleniumTests/Tests_MDE.side
  xml/dataset2.xml
  xml/dataset3.xml
Labels: bug

#409 Fix: Saving dataset with identical DOI or without DOI
  doc/changelog.html
  save/formgroups/save_resourceinformation_and_rights.php
  tests/SaveResourceInformationAndRightsTest.php
  vendor/composer/installed.php
Labels: bug

#410 Fg dates
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/coverage.html
  formgroups/dates.html
  js/mappingXmlToInputFields.js
Labels: Feature Request

#440 Update Readme and Help Guide for Fg authors
  README.md
  doc/ER-Diagram.jpg
  doc/EntwurfFürDasDritteSpring.png
  doc/MDE2-MSL - ER-Modell MSL.jpg
  doc/MSL-Prototyp(11.10.2024).png
  doc/WireframeAktuellerStand.jpg
  doc/WireframeAktuellerStandDM.jpg
  doc/WireframeNextSprintVorschlag.jpg
  doc/help.html
  formgroups/authors.html
  formgroups/contactpersons.html
  formgroups/contributors.html
Labels: Dokumentation

#444 Fix: Increase of version number to 2.0.0RC2 and changes of project name and metadata
  CITATION.cff
  README.md
  api/v2/docs/swagger.yaml
  composer.json
  composer.lock
  doc/help.html
  lang/de.json
  lang/en.json
  lang/fr.json
  modals.html
  vendor/composer/InstalledVersions.php
  vendor/composer/installed.php
Labels: Dokumentation

#442 Feature: Default value for timezone select field
  doc/changelog.html
  formgroups/coverage.html
  js/buttons.js
  js/select.js
Labels: Feature Request

#446 Update Readme + Help Guide for fg Resource Information
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/resourceInformation.html
  install.php
  js/buttons.js
  js/mappingXmlToInputFields.js
  schemas/DataCite/DataCiteExample45.xml
  tests/SaveResourceInformationAndRightsTest.php
  tests/SeleniumTests/Tests_MDE.side
  xml/resource_4.xml
Labels: Dokumentation, Feature Request

#453 Installation README.md Update
  README.md
Labels: Dokumentation

#461 Hotfix: GitHub Action für Selenium-Tests aktualisiert
  .github/workflows/selenium.yml
Labels: bug

#454 Update Readme + Help Guide + load from xml for fg Contributors
  README.md
  composer.lock
  doc/changelog.html
  doc/help.html
  formgroups/contributors.html
  js/affiliations.js
  js/autocomplete.js
  js/buttons.js
  js/mappingXmlToInputFields.js
  js/roles.js
  save/formgroups/save_authors.php
  save/formgroups/save_contributors.php
  schemas/Mappings/FreestyleToDatacite.mfd
  schemas/XSLT/MappingMapToDataCiteSchema45.xslt
  vendor/composer/installed.php
  xml/resource_4.xml
Labels: bug, Dokumentation

#459 Fix: fg Originating Laboratories: Plus-Button
  doc/changelog.html
  formgroups/contactpersons.html
  formgroups/originatingLaboratory.html
  formgroups/resourceInformation.html
Labels: bug

#466 Update Readme&Help Guide for fgs Originating Laboratories + Descriptions
  README.md
  doc/changelog.html
  doc/help.html
  formgroups/descriptions.html
  formgroups/originatingLaboratory.html
  install.php
  js/buttons.js
Labels: Dokumentation

#456 Feature: Optimized workflow for submitting dataset
  README.md
  doc/changelog.html
  footer.html
  js/saveHandler.js
  js/submitHandler.js
  js/validation.js
  lang/de.json
  lang/en.json
  lang/fr.json
  modals.html
  send_xml_file.php
Labels: Dokumentation, Feature Request
